/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shops */
        get: operations["list_shops_shops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shops/{shop_id}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Book
         * @description A1. Every figure here is computed by bahi/domain from the ledger.
         */
        get: operations["get_book_shops__shop_id__book_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shops/{shop_id}/counter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Counter
         * @description A2. Everyone who scanned the udhaar QR in the last three minutes.
         */
        get: operations["get_counter_shops__shop_id__counter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shops/{shop_id}/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Customers
         * @description Everyone in the book, for picking someone who is not at the counter.
         */
        get: operations["list_customers_shops__shop_id__customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shops/{shop_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Entry
         * @description Record udhaar: for a scan at the counter, or a customer from the book.
         */
        post: operations["record_entry_shops__shop_id__entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/join/{shop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join
         * @description B0. He scanned the shop's udhaar QR: he is at the counter.
         */
        post: operations["join_join__shop_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan
         * @description What happened to his scan. Once the shopkeeper records an amount, the entry
         *     comes back here and his phone shows the confirmation sheet.
         */
        get: operations["get_scan_scans__scan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Leave
         * @description He tapped Cancel.
         */
        post: operations["leave_scans__scan_id__leave_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entry */
        get: operations["get_entry_entries__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm
         * @description B1. "Yes, I owe ₹200".
         */
        post: operations["confirm_entries__entry_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispute
         * @description B1. "That's not right".
         */
        post: operations["dispute_entries__entry_id__dispute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shops/{shop_id}/heard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Heard Text
         * @description Words typed or tapped: the same rules as speech, without the recogniser.
         */
        post: operations["heard_text_shops__shop_id__heard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shops/{shop_id}/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Heard Voice
         * @description A recording from the shop's mic. 503 when voice is offline and it isn't a
         *     recording we have heard before; the screen then asks him to type it.
         */
        post: operations["heard_voice_shops__shop_id__voice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voice/clips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Clips
         * @description The demo recordings on disk, for playing into /voice with the wifi off.
         */
        get: operations["list_clips_voice_clips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voice/clips/{slug}.wav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clip */
        get: operations["get_clip_voice_clips__slug__wav_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskOut */
        AskOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ask";
            /**
             * Why
             * @enum {string}
             */
            why: "who" | "nobody" | "not_found" | "several";
            /** Among */
            among: components["schemas"]["PersonOut"][];
        };
        /** Body_heard_voice_shops__shop_id__voice_post */
        Body_heard_voice_shops__shop_id__voice_post: {
            /** Audio */
            audio: string;
        };
        /** BookOut */
        BookOut: {
            /** Customer Count */
            customer_count: number;
            /** Invited Count */
            invited_count: number;
            /** Owing Count */
            owing_count: number;
            /** Outstanding Paise */
            outstanding_paise: number;
            /** Lines */
            lines: components["schemas"]["LineOut"][];
        };
        /** ClipOut */
        ClipOut: {
            /** Slug */
            slug: string;
            /** Label */
            label: string;
            /** Shows */
            shows: string;
        };
        /**
         * CounterOut
         * @description Everyone at the counter, oldest scan first.
         */
        CounterOut: {
            /** Shop Id */
            shop_id: string;
            /** Waiting */
            waiting: components["schemas"]["WaitingOut"][];
        };
        /** CustomerOut */
        CustomerOut: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Tag */
            tag: string | null;
            /**
             * Joined
             * @enum {string}
             */
            joined: "linked" | "invited" | "name_only";
        };
        /** DisputeIn */
        DisputeIn: {
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Reason */
            reason?: string | null;
        };
        /** EntryOut */
        EntryOut: {
            /** Id */
            id: string;
            /** Customer Id */
            customer_id: string;
            /** Display Name */
            display_name: string;
            /** Shop Id */
            shop_id: string;
            /** Shop Name */
            shop_name: string;
            /** Amount Paise */
            amount_paise: number;
            /** Paid Paise */
            paid_paise: number;
            /**
             * Status
             * @enum {string}
             */
            status: "recorded" | "confirmed" | "disputed" | "corrected" | "settled";
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Note */
            note: string | null;
            /** Spoken Text */
            spoken_text: string | null;
            /** Corrects Entry Id */
            corrects_entry_id: string | null;
            /** Acknowledged At */
            acknowledged_at: string | null;
            /** Button */
            button: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
            /**
             * Now
             * Format: date-time
             */
            now: string;
        };
        /**
         * HeardIn
         * @description What the shopkeeper said, typed or tapped instead of spoken.
         */
        HeardIn: {
            /** Text */
            text: string;
        };
        /**
         * HeardOut
         * @description What was heard, and what the rules made of it. Nothing is recorded yet.
         */
        HeardOut: {
            /** Transcript */
            transcript: string;
            /**
             * Source
             * @enum {string}
             */
            source: "typed" | "sarvam" | "sarvam_cached" | "clip_script";
            /** Name */
            name: string | null;
            /** Amount Paise */
            amount_paise: number | null;
            /** Amount Words */
            amount_words: string | null;
            /** Problem */
            problem: ("no_amount" | "unclear_amount") | null;
            readback: components["schemas"]["ReadbackOut"] | null;
            /** Who */
            who: components["schemas"]["PickedOut"] | components["schemas"]["AskOut"];
        };
        /**
         * JoinIn
         * @description He scanned the udhaar QR. A first-timer tells us the name to use.
         */
        JoinIn: {
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Name */
            name?: string | null;
        };
        /** JoinOut */
        JoinOut: {
            /** Customer Id */
            customer_id: string;
            /** Scan Id */
            scan_id: string;
            shop: components["schemas"]["ShopOut"];
            /** First Time */
            first_time: boolean;
        };
        /** LineOut */
        LineOut: {
            /** Customer Id */
            customer_id: string;
            /** Display Name */
            display_name: string;
            /** Tag */
            tag: string | null;
            /**
             * Joined
             * @enum {string}
             */
            joined: "linked" | "invited" | "name_only";
            /** Balance Paise */
            balance_paise: number;
            /** Day */
            day: number;
            /**
             * Chip
             * @enum {string}
             */
            chip: "on_rhythm" | "changed" | "not_confirmed" | "new";
            rhythm: components["schemas"]["RhythmOut"];
        };
        /** PersonIn */
        PersonIn: {
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
        };
        /** PersonOut */
        PersonOut: {
            /** Customer Id */
            customer_id: string;
            /** Display Name */
            display_name: string;
            /** Scan Id */
            scan_id: string | null;
        };
        /** PickedOut */
        PickedOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "picked";
            /**
             * How
             * @enum {string}
             */
            how: "only_one" | "at_counter" | "in_book";
            person: components["schemas"]["PersonOut"];
        };
        /**
         * ReadbackOut
         * @description The amount said back. Never a name: the Soundbox says only the amount.
         */
        ReadbackOut: {
            /** Roman */
            roman: string;
            /** Devanagari */
            devanagari: string;
        };
        /**
         * RecordIn
         * @description An udhaar entry. Either a scan (he is at the counter) or a customer.
         */
        RecordIn: {
            /** Amount Paise */
            amount_paise: number;
            /** Scan Id */
            scan_id?: string | null;
            /** Customer Id */
            customer_id?: string | null;
            /** Note */
            note?: string | null;
            /** Spoken Text */
            spoken_text?: string | null;
        };
        /** RhythmOut */
        RhythmOut: {
            /** N */
            n: number;
            /** Median Gap */
            median_gap: number | null;
            /** Max Gap */
            max_gap: number | null;
            /** Last Paid */
            last_paid: string | null;
        };
        /** ScanOut */
        ScanOut: {
            /** Scan Id */
            scan_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "waiting" | "recorded" | "left" | "expired";
            entry: components["schemas"]["EntryOut"] | null;
        };
        /**
         * ShopBookOut
         * @description The shopkeeper's book. Also written to contract/shop.json by `make db`.
         */
        ShopBookOut: {
            /**
             * Synthetic
             * @default true
             * @constant
             */
            synthetic: true;
            /**
             * About
             * @default Synthetic demo data for one seeded shop.
             */
            about: string;
            /**
             * Today
             * Format: date
             */
            today: string;
            shop: components["schemas"]["ShopOut"];
            book: components["schemas"]["BookOut"];
        };
        /** ShopOut */
        ShopOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Locality */
            locality: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WaitingOut */
        WaitingOut: {
            /** Scan Id */
            scan_id: string;
            /** Customer Id */
            customer_id: string;
            /** Display Name */
            display_name: string;
            /** Tag */
            tag: string | null;
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            /** Waited S */
            waited_s: number;
            /** First Time */
            first_time: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_shops_shops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOut"][];
                };
            };
        };
    };
    get_book_shops__shop_id__book_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopBookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_counter_shops__shop_id__counter_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_customers_shops__shop_id__customers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_entry_shops__shop_id__entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_join__shop_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_scans__scan_id__leave_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entry_entries__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_entries__entry_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispute_entries__entry_id__dispute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heard_text_shops__shop_id__heard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeardIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heard_voice_shops__shop_id__voice_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_heard_voice_shops__shop_id__voice_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clips_voice_clips_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipOut"][];
                };
            };
        };
    };
    get_clip_voice_clips__slug__wav_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
