"""What goes over the wire, as Pydantic models.

These are the API contract. FastAPI turns them into the OpenAPI spec, and the
frontend's TypeScript types are generated from that spec (`make openapi`), so a
field renamed here breaks the frontend's type check rather than its screens.

Pydantic lives here and nowhere else. The domain uses frozen dataclasses, so the
purity test needs no exceptions.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field

from bahi.domain.book import Chip, Joined

EntryStatus = Literal["recorded", "confirmed", "disputed", "corrected", "settled"]


class ShopOut(BaseModel):
    id: str
    name: str
    locality: str


class RhythmOut(BaseModel):
    n: int
    median_gap: int | None
    max_gap: int | None
    last_paid: date | None


class LineOut(BaseModel):
    customer_id: str
    display_name: str
    tag: str | None
    joined: Joined
    balance_paise: int
    day: int
    chip: Chip
    rhythm: RhythmOut


class BookOut(BaseModel):
    customer_count: int
    invited_count: int
    owing_count: int
    outstanding_paise: int
    lines: list[LineOut]


class ShopBookOut(BaseModel):
    """The shopkeeper's book. Also written to contract/shop.json by `make db`."""

    synthetic: Literal[True] = True
    about: str = "Synthetic demo data for one seeded shop."
    today: date
    shop: ShopOut
    book: BookOut


class CustomerOut(BaseModel):
    id: str
    display_name: str
    tag: str | None
    joined: Joined


class WaitingOut(BaseModel):
    scan_id: str
    customer_id: str
    display_name: str
    tag: str | None
    scanned_at: datetime
    #: Seconds since he scanned, by the server's clock. The browser's clock may
    #: disagree with the product's (the demo pins the date), so it never does this sum.
    waited_s: int
    first_time: bool


class CounterOut(BaseModel):
    """Everyone at the counter, oldest scan first."""

    shop_id: str
    waiting: list[WaitingOut]


class EntryOut(BaseModel):
    id: str
    customer_id: str
    display_name: str
    shop_id: str
    shop_name: str
    amount_paise: int
    paid_paise: int
    status: EntryStatus
    recorded_at: datetime
    note: str | None
    spoken_text: str | None
    corrects_entry_id: str | None
    acknowledged_at: datetime | None
    #: The confirm button's words, generated by the server so that what he taps
    #: and what is stored are the same string.
    button: str


class RecordIn(BaseModel):
    """An udhaar entry. Either a scan (he is at the counter) or a customer."""

    amount_paise: int = Field(gt=0)
    scan_id: UUID | None = None
    customer_id: UUID | None = None
    note: str | None = Field(default=None, max_length=80)
    spoken_text: str | None = Field(default=None, max_length=200)


class JoinIn(BaseModel):
    """He scanned the udhaar QR. A first-timer tells us the name to use."""

    person_id: UUID
    name: str | None = Field(default=None, min_length=1, max_length=40)


class JoinOut(BaseModel):
    customer_id: str
    scan_id: str
    shop: ShopOut
    first_time: bool


class ScanOut(BaseModel):
    scan_id: str
    state: Literal["waiting", "recorded", "left", "expired"]
    entry: EntryOut | None


class PersonIn(BaseModel):
    person_id: UUID


class DisputeIn(BaseModel):
    person_id: UUID
    reason: str | None = Field(default=None, max_length=280)


# ── voice ────────────────────────────────────────────────────────────────────


class HeardIn(BaseModel):
    """What the shopkeeper said, typed or tapped instead of spoken."""

    text: str = Field(min_length=1, max_length=200)
    #: What he said before, when this answers "कितने रुपये?" or "उधार या जमा?":
    #: "Sharma ko", then "do sau", is read as one sentence.
    before: str | None = Field(default=None, max_length=400)


class PersonOut(BaseModel):
    customer_id: str
    display_name: str
    #: Room, wing or work: how the shopkeeper tells two Anubhavs apart.
    tag: str | None
    #: His scan, if he is at the counter: the entry should use it.
    scan_id: str | None


class PickedOut(BaseModel):
    kind: Literal["picked"] = "picked"
    #: Why him: the only one waiting, the words fit him at the counter, or in the book.
    how: Literal["only_one", "at_counter", "in_book"]
    person: PersonOut


class AskOut(BaseModel):
    kind: Literal["ask"] = "ask"
    #: who: several waiting, no name. nobody: nobody waiting, no name.
    #: several: the words fit more than one. maybe: only a weak match, offered.
    #: not_found: the words fit nobody. not_said: the reader quoted words not said.
    why: Literal["who", "nobody", "several", "maybe", "not_found", "not_said"]
    among: list[PersonOut]


class ReadbackOut(BaseModel):
    """The amount said back. Never a name: the Soundbox says only the amount."""

    roman: str
    devanagari: str


class CheckOut(BaseModel):
    """One check our code made on the reading."""

    kind: Literal["amount_said", "amount_read", "person_said", "person_fits"]
    ok: bool
    #: The check, in the shopkeeper's words.
    says: str


#: typed; sarvam (live); sarvam_cached (Sarvam heard this recording before);
#: clip_script (a demo clip not yet run through Sarvam: its script, not a transcript)
HeardSource = Literal["typed", "sarvam", "sarvam_cached", "clip_script"]


class HeardOut(BaseModel):
    """What was heard, what read it, and what our checks made of it. Nothing is
    recorded yet."""

    transcript: str
    source: HeardSource
    #: sarvam: Sarvam-105B read the words. rules: our parser did.
    reader: Literal["sarvam", "rules"]
    #: Why our parser read it: voice is offline, or Sarvam-105B gave no usable answer.
    fallback: Literal["offline", "no_answer"] | None
    #: udhaar is the only one recorded here. A payment is shown, not recorded (V3).
    intent: Literal["udhaar", "payment", "unclear"]
    #: The words that name the person, as the reader quoted them.
    name: str | None
    #: Our parser's reading of the amount words. None unless every amount check passed.
    amount_paise: int | None
    amount_words: str | None
    problem: (
        Literal[
            "no_amount",
            "unclear_amount",
            "amount_not_said",
            "amount_mismatch",
            "invented_customer",
        ]
        | None
    )
    checks: list[CheckOut]
    readback: ReadbackOut | None
    who: PickedOut | AskOut = Field(discriminator="kind")


class AnswerIn(BaseModel):
    """His answer to "किसके लिए?", typed."""

    text: str = Field(min_length=1, max_length=200)
    #: Who the screen offered. Empty: anyone at the counter or in the book.
    among: list[UUID] = Field(default_factory=list, max_length=60)


class AnswerOut(BaseModel):
    """Who the answer names, or the question again. The amount is the one already
    heard; nothing is recorded yet."""

    transcript: str
    source: HeardSource
    who: PickedOut | AskOut = Field(discriminator="kind")


class ClipOut(BaseModel):
    slug: str
    label: str
    shows: str


# ── the munshi ───────────────────────────────────────────────────────────────


class MunshiIn(BaseModel):
    """His words, typed. No conversation_id: a new conversation."""

    conversation_id: UUID | None = None
    text: str = Field(min_length=1, max_length=400)


class CardOut(BaseModel):
    """The entry the munshi proposed, as the card shows it. The amount is the one
    stored on the draft, never the munshi's sentence."""

    draft_id: UUID
    #: None until his yes adds someone new to the book.
    customer_id: UUID | None
    display_name: str
    tag: str | None
    #: None on a card that only adds someone.
    amount_paise: int | None
    #: customer: only adds someone new to the book, by name. correction: the
    #: right amount for an entry already written.
    kind: Literal["udhaar", "payment", "customer", "correction"]
    #: A correction: what the entry said.
    corrects_amount_paise: int | None = None
    #: Someone not in the book yet: his yes adds them, by name only.
    new: bool
    #: shown: waiting for his yes. saved: written. cancelled: he said no.
    status: Literal["shown", "saved", "replaced", "cancelled"]
    #: Why it waits for a clear yes; empty means the three-second countdown.
    reasons: list[Literal["weak_match", "large", "unusual", "new_customer", "correction"]]
    #: What he said, shown under the amount.
    spoken_text: str | None
    entry_id: UUID | None
    #: The customer has BAHI on his phone, so a saved entry reaches it.
    on_bahi: bool


class MunshiOut(BaseModel):
    conversation_id: UUID
    #: What the mic heard, or what he typed. None for a tap.
    heard: str | None
    source: Literal["typed", "sarvam", "sarvam_cached", "clip_script", "tap"]
    #: The munshi's reply, to show and to say.
    reply: str | None
    #: The reply in Sarvam's voice.
    say_url: str | None
    #: What the munshi did this turn: "Looked for B wing: 8 found".
    done: list[str]
    card: CardOut | None
    #: A card was saved or taken away this turn: the conversation can rest.
    finished: bool


# ── chat (V5) ────────────────────────────────────────────────────────────────


class ThreadEntryOut(BaseModel):
    """An entry, as its card in a thread shows it: now, not when it was posted."""

    id: str
    amount_paise: int
    paid_paise: int
    status: EntryStatus
    recorded_at: datetime
    note: str | None
    #: The entry this one corrects, and what it said.
    corrects_entry_id: str | None
    corrects_amount_paise: int | None
    disputed_at: datetime | None
    acknowledged_at: datetime | None
    last_paid_at: datetime | None
    last_method: Literal["upi", "cash"] | None
    #: Past the limitation line: kept, and claims nothing.
    expired: bool
    #: The confirm button's words, for the customer's side.
    button: str


class MessageOut(BaseModel):
    id: str
    author: Literal["shop", "customer", "bahi"]
    kind: Literal["text", "entry", "reminder"]
    body: str
    sent_at: datetime
    entry: ThreadEntryOut | None
    #: The entry's first message draws its card; later ones about the same entry
    #: (a dispute, a payment) are one line.
    card: bool


class ThreadOut(BaseModel):
    """One shop and one customer, from either side."""

    #: The product's today (the demo pins the date), for "Today" and "Yesterday".
    today: date
    thread_id: str | None
    customer_id: str
    shop: ShopOut
    #: The name the shop keeps him under, and its description.
    display_name: str
    tag: str | None
    joined: Joined
    balance_paise: int
    #: Days since he last paid, when he owes something.
    day: int | None
    messages: list[MessageOut]
    #: A reminder planned for him, and when it goes.
    reminder_at: datetime | None


class InboxRowOut(BaseModel):
    customer_id: str
    display_name: str
    tag: str | None
    joined: Joined
    author: Literal["shop", "customer", "bahi"]
    kind: Literal["text", "entry", "reminder"]
    body: str
    sent_at: datetime
    #: The last message's entry, for the row's status line.
    entry: ThreadEntryOut | None
    #: The last message is that entry's card, not a line about it (a payment).
    card: bool
    unread: int
    #: He wrote last, or he says an entry is wrong.
    needs_reply: bool
    reminder_at: datetime | None


class InboxOut(BaseModel):
    today: date
    rows: list[InboxRowOut]
    unread: int


class SayIn(BaseModel):
    text: str = Field(min_length=1, max_length=500)


class CustomerSayIn(BaseModel):
    person_id: UUID
    text: str = Field(min_length=1, max_length=500)


class RepliesOut(BaseModel):
    """Replies the munshi suggests. Only offered: nothing is sent until he taps."""

    replies: list[str]


class CorrectIn(BaseModel):
    amount_paise: int = Field(gt=0)


# ── the customer's own book (V3) ─────────────────────────────────────────────


class MyShopOut(BaseModel):
    shop: ShopOut
    customer_id: str
    #: What the shop calls him.
    display_name: str
    balance_paise: int
    #: What he can pay now: his balance less anything he says is wrong.
    payable_paise: int
    #: Days since he last paid here, when he owes something.
    day: int | None
    entries: list[ThreadEntryOut]
    unread: int


class InviteOut(BaseModel):
    shop: ShopOut
    display_name: str
    invited_at: datetime


class MyUdhaarOut(BaseModel):
    today: date
    person_id: str
    total_paise: int
    #: Every shop whose book he is in, the ones he owes first.
    shops: list[MyShopOut]
    invites: list[InviteOut]


class PayIn(BaseModel):
    """He pays this shop by UPI: what he owes it, or the part he chose."""

    person_id: UUID
    #: None pays everything he owes this shop.
    amount_paise: int | None = Field(default=None, gt=0)


class PaidOut(BaseModel):
    shop: ShopOut
    amount_paise: int
    #: What he still owes this shop after it.
    left_paise: int
    paid_at: datetime
    method: Literal["upi"]
    #: From the oldest entry it paid to today.
    settled_in: int
    entry_ids: list[str]
    #: What he still owes at other shops.
    elsewhere: list[MyShopOut]


class DemoPhoneOut(BaseModel):
    person_id: str
    name: str
    #: Where he lives or works, as the shop that added him first describes him.
    tag: str | None
    #: linked: in at least one book. invited: waiting for his yes. paytm: on
    #: Paytm, in nobody's book yet.
    state: Literal["linked", "invited", "paytm"]
    #: How many shops' books he is in.
    shops: int


# ── adding someone who can't scan (V6) ───────────────────────────────────────


class AccountOut(BaseModel):
    """The Paytm account behind a number or UPI ID. The number is not kept."""

    person_id: str
    name: str
    #: Already in this shop's book: linked, or invited and waiting.
    here: Joined | None


class InviteIn(BaseModel):
    #: A mobile number or UPI ID, looked up again here and never stored.
    query: str = Field(min_length=3, max_length=60)
    tag: str | None = Field(default=None, max_length=40)


class NameOnlyIn(BaseModel):
    display_name: str = Field(min_length=1, max_length=40)
    tag: str | None = Field(default=None, max_length=40)


# ── Tonight (V4) ─────────────────────────────────────────────────────────────


TonightWhy = Literal[
    "past_longest_gap",
    "inside_gap",
    "not_confirmed",
    "disputed",
    "too_new",
    "no_phone",
    "reminded",
]


class ReminderOut(BaseModel):
    id: str
    send_at: datetime
    body: str
    #: munshi: Sarvam's model wrote it, and it passed our checks. words: ours.
    written: Literal["munshi", "words"]
    status: Literal["planned", "stopped", "sent"]


class PlanOut(BaseModel):
    customer_id: str
    display_name: str
    tag: str | None
    joined: Joined
    balance_paise: int
    day: int
    rhythm: RhythmOut
    send: bool
    why: TonightWhy
    reminded_on: date | None
    reminder: ReminderOut | None


class TonightOut(BaseModel):
    today: date
    for_day: date
    worked_out_at: datetime
    owing_count: int
    sending_count: int
    #: Everyone who owes, the ones reminded first, then alphabetical.
    plans: list[PlanOut]


class SentOut(BaseModel):
    sent: int


# ── the Soundbox (V7) ────────────────────────────────────────────────────────


class EventOut(BaseModel):
    """Something the shop should hear about. The Soundbox plays a tone, or says
    an amount; it never says a name. The screen shows who."""

    kind: Literal["scanned", "confirmed", "disputed", "paid", "message"]
    at: datetime
    customer_id: str
    display_name: str
    amount_paise: int | None
    #: After a payment: what he still owes the shop now.
    left_paise: int | None = None


class EventsOut(BaseModel):
    #: Ask again with this as `after`.
    now: datetime
    events: list[EventOut]
