"""Writes contract/shop.json: the shopkeeper's book, as the API will serve it.

Generated from the seeded database by the same domain code the API will run, and
never edited by hand. The frontend builds its first screen against this file
before the API exists; when the read endpoint lands, it returns this same shape,
so the switch changes where the numbers come from and not what they are.

    uv run python -m data.contract
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from bahi.domain.book import Book, Line, book
from bahi.store import book as store
from data import db
from data.world import HOME, SEED, SHOPS, TODAY, uid

CONTRACT = Path(__file__).resolve().parents[2] / "contract" / "shop.json"


def line(ln: Line) -> dict[str, Any]:
    r = ln.rhythm
    return {
        "customer_id": ln.customer_id,
        "display_name": ln.display_name,
        "tag": ln.tag,
        "joined": ln.joined,
        "balance_paise": ln.balance_paise,
        "day": ln.day,
        "chip": ln.chip,
        "rhythm": {
            "n": r.n,
            "median_gap": r.median_gap,
            "max_gap": r.max_gap,
            "last_paid": r.last_paid.isoformat() if r.last_paid else None,
        },
    }


def payload(b: Book) -> dict[str, Any]:
    name, locality = SHOPS[HOME]
    return {
        "synthetic": True,
        "about": "Synthetic demo data for one seeded shop. Generated by "
        "`make db`; do not edit by hand.",
        "seed": SEED,
        "today": b.today.isoformat(),
        "shop": {"id": str(uid("shop", HOME)), "name": name, "locality": locality},
        "book": {
            "customer_count": b.customer_count,
            "invited_count": b.invited_count,
            "owing_count": b.owing_count,
            "outstanding_paise": b.outstanding_paise,
            "lines": [line(ln) for ln in b.lines],
        },
    }


def build(con: db.Conn) -> dict[str, Any]:
    return payload(book(store.load(con, str(uid("shop", HOME))), TODAY))


def write(con: db.Conn) -> Path:
    CONTRACT.parent.mkdir(exist_ok=True)
    text = json.dumps(build(con), indent=2, ensure_ascii=False) + "\n"
    CONTRACT.write_text(text, encoding="utf-8")
    return CONTRACT


def main() -> int:
    with db.connect() as con:
        print(f"  wrote {write(con)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
